### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by peti** [gcross/AbortT-transformers#1]
AbortT-transformers-1.0.1 fails to compile on my machine with the following error message:

```
Setup: At least the following dependencies are missing:
QuickCheck >=2.4 && <2.6,
test-framework ==0.6.*,
test-framework-hunit ==0.2.*,
test-framework-quickcheck2 ==0.2.*
```

I removed the upper bounds on those dependencies from the Cabal file, tried again, and then the build succeeded fine, so I guess it would be okay to allow current versions of these packages. Could you please edit the Cabal file on Hackage accordingly or release a new version?

**Comment by gcross** [comment]
Done!  Sorry about the delay; I wasn't feeling well last week.  Thanks for letting me know!
